environment_config:
  path: utils/config.dart # optional, result file path against `lib/` folder
  dotenv_path: .env # optional, result file path for .env file against project root folder
  class: HabitatConfig

  fields:
    BASE_URL:
      short_name: u
      default: https://api.rotary.club
